### PR TITLE
add import of narrowPeak file

### PR DESCRIPTION
**Pull request by phaverty**
Thusly?  If so, I'll add broadPeak and then docs for narrowPeak and broadPeak.

### CODE REVIEW

**Comment by lawremi** [comment]
Thanks. Not sure what I think about the lower case "narrowPeakFile" class name. Other than that, please proceed.

**Comment by phaverty** [comment]
OK, I think I'm finished now.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by lawremi** [comment]
Sorry to be so pedantic but I think `import.NarrowPeak` should be `import.narrowPeak`. If you agree, just make that change and I'll merge it.

**Comment by phaverty** [comment]
Done. Oops, I thought the X in import.X was to be the class name rather
than the file suffix.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Pull request merged**
